### ISSUE TITLE
The Slide counter vs. the URL+Title modules

### ISSUE THREAD

**Issue by JanecekPetr** [ondras/jsslides#5]
I'm not very happy with the difference between the slide numbering mechanism (the one via CSS) and the URL+title modules.
The slide mechanism numbers the slides from 0 while title+URL from 1. An annoying inconsistency which is completely invisible while presenting.

Would you accept a patch to do one of the following and if yes, which one would you prefer?
1. Change URL+title modules to count from 0, too.
2. Change URL+title modules to count from 0, too, but make the 0th slide number invisible (just as the slides counter)
3. Add an additional formatting for Title (additionaly to `n`) which would count from 0. The URL would then either have to be inconsistent or smartly mimic the title (this assumes merging the two modules togeher)
4. Add a new setting, `Slides.countSlidesFrom` or something - defaulting to 1. This could potentially be accompanied with dropping the CSS counter and making it a central JS counter that could be used for all three things - optionally settable to automatically add a slide number to the presentation.
5. Something else entirely.

**Comment by ondras** [comment]
So basically the whole issue is caused by [this CSS rule](https://github.com/ondras/jsslides/blob/master/v3/slides/slides3.css#L21), right? 

Generally speaking, I would like to refactor all the stuff relevant to CSS counters into a separate module (right now, it is mixed into `slides3.css` and `skin/seznam/skin.css`).

This module could be further *configured* using some HTML/CSS tricks, as in 
```html
<section class="slide" data-counter="skip">
```

```css
.slide:not([data-counter=skip]) {
  counter-increment: slide;
}
```

At the end of the day, the *HTML* part will define how is the numbering going to behave; the *CSS* part will influence how it looks.

URL/Title numbering is okay for me right now, as these numbers are processed by humans and not machines.

(Also, URL/Title and CSS are never going to be 100% aligned, because of http://ondras.zarovi.cz/slides/webmasters/#5 and similar.)

**Comment by JanecekPetr** [comment]
> So basically the whole issue is caused by this CSS rule, right?

Yep.

Unfortunately for the JS code, the rule makes aesthetical sense - the first (zero<sup>th</sup>) slide stands out and is more of a book cover than a normal book page with content.

A standalone module is fine, I might get to getting that done over the weekend. And I guess instead of having a personal fork maintaining the JS counter zero-based, I'll simply use a Title template without `%n`. Feel free to close this (or use it as a don't-forget-to-refactor-css-counter issue).

**Comment by ondras** [comment]
> I'll simply use a Title template without %n

Hmmh, how does `%{n-1}` sound?

**Comment by JanecekPetr** [comment]
Better than the current status quo, but it will get redundant (and incorrect) again once you introduce the slide-counter module.

**Comment by ondras** [comment]
The general approach is to have these two (url+title vs. css) independent. And `%{n-1}` allows for some *configurability*, which is currently missing...

**Comment by ondras** [comment]
Separate numbering module: https://github.com/ondras/jsslides/commit/83bdb02f4419210d6fc2cf765b3fd98719a0b07f

**Comment by ondras** [comment]
Numbering docs: https://github.com/ondras/jsslides/wiki/Modules#numbering

**Comment by ondras** [comment]
Expressions in template strings: https://github.com/ondras/jsslides/commit/0e644a8c05d14f4e0d2d59102398015ee6fb04c3

(e.g. `%{n+3}`)

**Comment by ondras** [comment]
URL, Title and CSS numberings are now (hopefully) completely configurable.

**Comment by JanecekPetr** [comment]
You're actually the best. Thanks!
